### PR TITLE
fix: cfg not validating entry/exit types

### LINKED ISSUE #1189: CFG nodes do not fail validation when their input ports do not match the input node of the entry block
see https://github.com/CQCL/guppylang/issues/242 for an example

### PR DESCRIPTION
**Pull request by ss2165**
Closes #1189

Failing example generated using hugr-py

### CODE REVIEW

File: hugr-core/src/hugr/validate/test.rs [hunk 1]
```diff
@@ -926,6 +929,13 @@ fn cfg_children_restrictions() {
     b.remove_node(exit2);
 
     // Change the types in the BasicBlock node to work on qubits instead of bits
+    b.replace_op(
```
Comment (ss2165) [inline hugr-core/src/hugr/validate/test.rs:932]: this test failed because it was getting away with not updating the cfg op beforehand
