### PR TITLE
fix: dfg wrapper build handles incorrect output wire numbers

### LINKED ISSUE #1257: When building a TailLoop, calling `outputs_arr`, you are given an `OrderEdge` "output wire"
Cleanup + reproducer to come.

### PR DESCRIPTION
**Pull request by ss2165**
DFGWrapper handles incorrectly were using internal dfg output number as the outputs from the container node. Fixed for function, case and tailloop. Also fixed a test that relied on this incorrect behaviour.

Closes #1257

### CODE REVIEW

File: hugr-core/src/builder/handle.rs [hunk 1]
```diff
@@ -87,17 +87,7 @@ impl From<BuildHandle<DfgID>> for BuildHandle<CaseID> {
     fn from(value: BuildHandle<DfgID>) -> Self {
         Self {
             node_handle: value.node().into(),
-            num_value_outputs: value.num_value_outputs,
-        }
-    }
-}
-
-impl From<BuildHandle<DfgID>> for BuildHandle<TailLoopID> {
```
Comment (aborgna-q) [inline hugr-core/src/builder/handle.rs:95]: Could we keep the implementation (dropping the loop flag output)?

**Review by aborgna-q — APPROVED** [review]
LGTM

File: hugr-core/src/builder/handle.rs (hunk 1 above)
Comment (ss2165) [reply hugr-core/src/builder/handle.rs:95]: there may be some outputs embedded in the loop flag output in the "break" variant of the Sum.
