### PR TITLE
fix: Preserve offset for CFG edges when serializing to JSON

### LINKED ISSUE #2592: Model round-trip fails for some hugrs
The attached file (in json envelope format) provides an example.

[test_shortcircuit_assign3.hugr.json](https://github.com/user-attachments/files/22597770/test_shortcircuit_assign3.hugr.json)

```rust
use hugr::envelope::{write_envelope, EnvelopeConfig};
use hugr::{
    envelope::read_envelope, std_extensions::std_reg
};
use std::fs::File;
use std::io::{BufReader, Cursor};

fn main() {
    let f = File::open("test_shortcircuit_assign3.hugr.json").unwrap();
    let data = BufReader::new(f);
    let (_, pkg) = read_envelope(data, &std_reg()).unwrap();

    let mut data1: Vec<u8> = Vec::new();
    let _ = write_envelope(&mut data1, &pkg, EnvelopeConfig::binary());

    let buff1 = Cursor::new(data1);
    let _ = read_envelope(buff1, &std_reg()).unwrap();
}
```

The last line generates an error:
```
called `Result::unwrap()` on an `Err` value: ModelImport { source: ImportError { inner: Unsupported("Link (RegionId(1), LinkIndex(15)) would require a hyperedge because it connects more than one input port with more than one output port."), generator: Some("guppylang (guppylang-internals-v0.24.0)-v0.21.5") } }
```

Note: this test file was generated by running `just export-integration-tests` in the CQCL/guppylang repo. That produces a large number of files, of which only 8 exhibit this issue, namely:
* test_while_break.hugr
* test_shortcircuit_assign4.hugr
* test_if_expr_nested.hugr
* test_arith_big.hugr
* test_shortcircuit_assign3.hugr
* test_shortcircuit_assign2.hugr
* test_shortcircuit_assign1.hugr
* test_drop_while.hugr

The hugr files were converted to json using the CLI tool built on a branch containing [this fix](https://github.com/CQCL/hugr/pull/2590).

### LINKED ISSUE #2600: JSON serialization forgets offsets for edges between dataflow blocks in CFGs
[A.zip](https://github.com/user-attachments/files/22641851/A.zip)

The attached zipfile contains a binary envelope that encodes a hugr containing a CFG.

Unzip it and run the following:

```rust
use hugr::envelope::{write_envelope, EnvelopeConfig};
use hugr::{
    envelope::read_envelope, std_extensions::std_reg
};
use std::fs::File;
use std::io::{BufReader, Cursor};

fn main() {
    let f = File::open("A").unwrap();
    let data = BufReader::new(f);
    let (_, pkg) = read_envelope(data, &std_reg()).unwrap();
    pkg.validate().unwrap(); // OK

    let mut data1: Vec<u8> = Vec::new();
    let _ = write_envelope(&mut data1, &pkg, EnvelopeConfig::text());

    let buff1 = Cursor::new(data1);
    let (_, pkg1) = read_envelope(buff1, &std_reg()).unwrap();
    pkg1.validate().unwrap(); // NOK
}
```

This produces the error:
```
thread 'main' panicked at src/main.rs:19:21:
called `Result::unwrap()` on an `Err` value: Validation(InvalidEdges { parent: Node(4), parent_optype: CFG(CFG { signature: FuncTypeBase { input: TypeRowBase { types: [TypeBase(Extension(CustomType { extension: IdentList("tket.bool"), extension_ref: (Weak), id: "bool", args: [], bound: Copyable }), Copyable), TypeBase(Extension(CustomType { extension: IdentList("arithmetic.int.types"), extension_ref: (Weak), id: "int", args: [BoundedNat(6)], bound: Copyable }), Copyable)] }, output: TypeRowBase { types: [TypeBase(Extension(CustomType { extension: IdentList("tket.bool"), extension_ref: (Weak), id: "bool", args: [], bound: Copyable }), Copyable)] } } }), source: CFGEdgeSignatureMismatch { edge: ChildrenEdgeData { source: Node(5), target: Node(7), source_op: DataflowBlock(DataflowBlock { inputs: TypeRowBase { types: [TypeBase(Extension(CustomType { extension: IdentList("tket.bool"), extension_ref: (Weak), id: "bool", args: [], bound: Copyable }), Copyable), TypeBase(Extension(CustomType { extension: IdentList("arithmetic.int.types"), extension_ref: (Weak), id: "int", args: [BoundedNat(6)], bound: Copyable }), Copyable)] }, other_outputs: TypeRowBase { types: [] }, sum_rows: [TypeRowBase { types: [TypeBase(Extension(CustomType { extension: IdentList("arithmetic.int.types"), extension_ref: (Weak), id: "int", args: [BoundedNat(6)], bound: Copyable }), Copyable), TypeBase(Extension(CustomType { extension: IdentList("tket.bool"), extension_ref: (Weak), id: "bool", args: [], bound: Copyable }), Copyable)] }, TypeRowBase { types: [TypeBase(Extension(CustomType { extension: IdentList("tket.bool"), extension_ref: (Weak), id: "bool", args: [], bound: Copyable }), Copyable)] }] }), target_op: DataflowBlock(DataflowBlock { inputs: TypeRowBase { types: [TypeBase(Extension(CustomType { extension: IdentList("tket.bool"), extension_ref: (Weak), id: "bool", args: [], bound: Copyable }), Copyable)] }, other_outputs: TypeRowBase { types: [TypeBase(Extension(CustomType { extension: IdentList("tket.bool"), extension_ref: (Weak), id: "bool", args: [], bound: Copyable }), Copyable)] }, sum_rows: [TypeRowBase { types: [] }] }), source_port: Port(Outgoing, 0), target_port: Port(Incoming, 0) }, source_types: Some(TypeRowBase { types: [TypeBase(Extension(CustomType { extension: IdentList("arithmetic.int.types"), extension_ref: (Weak), id: "int", args: [BoundedNat(6)], bound: Copyable }), Copyable), TypeBase(Extension(CustomType { extension: IdentList("tket.bool"), extension_ref: (Weak), id: "bool", args: [], bound: Copyable }), Copyable)] }), target_types: TypeRowBase { types: [TypeBase(Extension(CustomType { extension: IdentList("tket.bool"), extension_ref: (Weak), id: "bool", args: [], bound: Copyable }), Copyable)] } } })
```

The reason is that there is a mismatch in types on one of the edges of the CFG. The first DFB within the CFG has two branches which expect different types (one `(i64, bool)` and one `(bool)`), and the types are assigned in the wrong order.

@aborgna-q points out that when we serialize the CFG edges in JSON format, we forget the offset for both the outgoing and the incoming ports: https://github.com/CQCL/hugr/blob/972532044f0fa7ae39b6c9b8bb2e5e7737698821/hugr-core/src/hugr/serialize.rs#L214-L220 .

This may be the root cause of #2592 .

### PR DESCRIPTION
**Pull request by cqc-alec**
Fixes #2592 . (Verified by regenerating JSON file using CLI built on this branch and rerunning test code.)
Fixes #2600 . (Verified by test included here.)

I don't think this counts as a breaking change to the JSON serialization format.

### CODE REVIEW

File: hugr-core/src/hugr/serialize.rs [hunk 1]
```diff
@@ -215,7 +215,8 @@ impl TryFrom<&Hugr> for SerHugrLatest {
             let op = hugr.get_optype(node);
             let is_value_port = offset < op.value_port_count(dir);
             let is_static_input = op.static_port(dir).is_some_and(|p| p.index() == offset);
-            let offset = (is_value_port || is_static_input).then_some(offset as u32);
+            let is_cfg_edge = op.is_dataflow_block();
+            let offset = (is_value_port || is_static_input || is_cfg_edge).then_some(offset as u32);
```
Comment (aborgna-q) [inline hugr-core/src/hugr/serialize.rs:219]: This is too restraining.
The bug any time we have more than one non-df ports, so it would be safer to do

```suggestion
            let multiple_other_ports = op.non_df_port_count(dir) > 1;
            let offset = (is_value_port || is_static_input || multiple_other_ports).then_some(offset as u32);
```

Alternatively, encode the offset always 🤷 

It's not a breaking serialization change either way since the decoding logic works fine if the offset is already defined

Comment (aborgna-q) [reply hugr-core/src/hugr/serialize.rs:219]: Ah, seems like `hugr-py` uses `None` only for order edges.

If we wanted to follow that here then we can check
```rust
let other_port_is_not_order = op.other_port_kind(dir) != EdgeKind::StateOrder
let offset = (is_value_port || is_static_input || other_port_is_not_order).then_some(offset as u32);
```

**Review by aborgna-q — APPROVED** [review]
