### PR TITLE
fix: Resolve types in `Value`s and custom consts

### LINKED ISSUE #1742: `OpaqueValue` should keep a `Weak<Extension>` pointer
Similarly to what we did with `ExtensionOp`s and `CustomType`s, `OpaqueValue`/`CustomConst` should keep a weak pointer to their extension and provide a `used_extensions` call.

### PR DESCRIPTION
**Pull request by aborgna-q**
Collects and resolves extensions in the types stored inside a `Value`. This includes the specified type of a `Sum` and other cached types.

Since we expect `CustomConst`'s `get_type` method to always return signatures computed by a binary definition.

For some reason there's a random test on `hugr-py` that starts failing when we enable this:
```
=================================== FAILURES ===================================
______________________________ test_higher_order _______________________________
Error parsing package: Error resolving opaque operation: Error in signature of operation 'prelude.Noop' in Node(3): Type arguments of node did not match params declared by definition: Wrong number of type arguments: 0 vs expected 1 declared type parameters
```

The fix for #1774 that I'm submitting immediately after this PR fixes it so I'm skipping the test in this PR 🤷 
I'll open an issue to investigate further after we make the release

### CODE REVIEW

File: hugr-core/src/extension/resolution/types.rs [hunk 1]
```diff
@@ -45,8 +45,7 @@ pub(crate) fn collect_op_types_extensions(
         OpType::FuncDefn(f) => collect_signature_exts(f.signature.body(), &mut used, &mut missing),
         OpType::FuncDecl(f) => collect_signature_exts(f.signature.body(), &mut used, &mut missing),
         OpType::Const(c) => {
-            let typ = c.get_type();
-            collect_type_exts(&typ, &mut used, &mut missing);
+            collect_value_exts(&c.value, &mut used, &mut missing);
         }
```
Comment (ss2165) [inline hugr-core/src/extension/resolution/types.rs:49]: nit: looks like the braces are no longer necessary

File: hugr-core/src/extension/resolution/types.rs [hunk 2]
```diff
@@ -221,3 +220,37 @@ fn collect_typearg_exts(
         _ => {}
     }
 }
+
+/// Collect the Extension pointers in the [`CustomType`]s inside a value.
+///
+/// # Attributes
+///
+/// - `arg`: The type argument to collect the extensions from.
```
Comment (ss2165) [inline hugr-core/src/extension/resolution/types.rs:228]:
```suggestion
/// - `value`: The value to collect the extensions from.
```

**Review by ss2165 — APPROVED** [review]
thanks for the nice comments :)
