### PR TITLE
fix: allow disconnected outputs in SiblingSubgraph::from_node

### LINKED ISSUE #1746: bug: `SiblingSubgraph::create_simple_replacement` compares signatures incorrectly
The function compares the signatures of the subgraph and replacement for equality:

https://github.com/CQCL/hugr/blob/4c1c6ee4c7d657c4bdb6b37c2237ae3f06b8d0be/hugr-core/src/hugr/views/sibling_subgraph.rs#L384-L385

However if the replacement had any disconnected outputs or multi-connected outputs this would fail because the current signature is calculated by iterating of the subgraph edges. 

Suggestion that this check is disabled as a temporary workaround and replaced with a correct signature computation for the current graph as a fix.

### PR DESCRIPTION
**Pull request by ss2165**
Uses `from_node` in lowering code to take advantage of this

Closes #1746

### CODE REVIEW

File: hugr-core/src/hugr/views/sibling_subgraph.rs [hunk 1]
```diff
@@ -277,9 +277,6 @@ impl SiblingSubgraph {
     ///
     /// The subgraph signature will be given by signature of the node.
     pub fn from_node(node: Node, hugr: &impl HugrView) -> Self {
-        // TODO once https://github.com/CQCL/portgraph/issues/155
```
Comment (ss2165) [inline hugr-core/src/hugr/views/sibling_subgraph.rs:280]: this comment is no longer true since the two methods have different functionality

If we can extend the functionality of `try_from_nodes` that would be great: #1766

**Comment by aborgna-q** [comment]
Do you mind rebasing on `main`?

**Review by aborgna-q — APPROVED** [review]
